<?php

namespace AppBundle\Repository;

/**
 * PreinscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreinscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
